<?php $insuranceRates = $this->getRates(); ?>
<?php $rate = $this->getRate(); ?>
<?php $address = $this->getAddress() ? $this->getAddress() : $this->getQuote()->getShippingAddress(); ?>

<?php if (isset($insuranceRates[$rate->getCode()]) && $insuranceRates[$rate->getCode()]['state']): ?>
    <div id="insuranceForShipping__<?php echo $rate->getCode() ?>"
         class="insuranceForShipping <?php echo $this->getShow() ? '' : 'insuranceForShipping-hidden' ?>">
        <?php $_insurance_method_price = ($insuranceRates[$rate->getCode()]['percent'] ? ($rate->getPrice() * ($insuranceRates[$rate->getCode()]['rate'] / 100)) : $insuranceRates[$rate->getCode()]['rate']);
        $insurance_method_price = $this->getQuote()->getStore()->convertPrice($_insurance_method_price, true) ?>
        <label><span><?php echo $this->__('Insurance') ?>
                &nbsp;<span>+<?php echo $insurance_method_price ?></span></span>
            <input class="insuranceForShipping__checkbox"
                   type="checkbox"
                   name="shipping_method_insurance"
                <?php if (($rate->getCode() === $address->getShippingMethod()) && (float)$address->getInsurance() > 0)
                    echo 'checked' ?>
                   value="<?php echo $_insurance_method_price ?>"></label>
    </div>
    <script>
        AdminOrder.prototype.setInsurance = function (insurance) {
            var data = {collect_shipping_rates: 1};
            data['order[shipping_method_insurance]'] = insurance;
            this.loadArea(['shipping_method', 'totals'], true, data);
        };

        $$('input[type="checkbox"][name="shipping_method_insurance"]').each(function (el) {
            Event.observe(el, 'click', function () {
                order.setInsurance(el.getValue());
            });
        });
    </script>
<?php endif; ?>
