<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php $_insurance = Mage::getModel('it_insurance/shipping')->getRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
            <dd>
                <ul>
                    <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                        <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                            <?php else: ?>
                            <?php if ($_sole) : ?>
                                <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                            <?php else: ?>
                            <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                            <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                    //]]>
                                </script>
                            <?php endif; ?>

                            <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                </label>

                            <?php //Insurance ?>
                            <?php if(isset($_insurance[$_rate->getCode()]) && $_insurance[$_rate->getCode()]['state']):?>
                                <div id="insuranceForShipping__<?php echo $_rate->getCode() ?>" class="insuranceForShipping <?php echo ($_rate->getCode()===$this->getAddressShippingMethod()||$_sole)?'':'insuranceForShipping-hidden' ?>">
                                    <?php $_insurance_method_price = ($_insurance[$_rate->getCode()]['percent']?($_rate->getPrice()*($_insurance[$_rate->getCode()]['rate']/100)):$_insurance[$_rate->getCode()]['rate']);
                                    $insurance_method_price = $this->getQuote()->getStore()->convertPrice($_insurance_method_price, true)?>
                                    <label><span><?php echo $this->__('Include the insurance?')?>(<span>+<?php echo $insurance_method_price ?></span>)</span>
                                        <input class="insuranceForShipping__checkbox"
                                               type="checkbox"
                                               name="shipping_method_insurance"
                                            <?php if (($_rate->getCode() === $this->getAddressShippingMethod() || $_sole) && (float)$this->getQuote()->getShippingAddress()->getInsurance() > 0) echo 'checked' ?> value="<?php echo $_insurance_method_price?>"></label>
                                </div>
                            <?php endif; ?>
                            <?php endif ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        //<![CDATA[
        <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
        <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function(el){
            Event.observe(el, 'click', function(){
                var getShippingCode = el.getValue();
                $$('input.insuranceForShipping__checkbox').each(function(ell){
                    ell.checked = false;
                });
                $$('div.insuranceForShipping').each(function (ell) {
                    ell.addClassName('insuranceForShipping-hidden');
                });

                if (el.checked === true) {
                    if($('insuranceForShipping__' + getShippingCode)){
                        $('insuranceForShipping__' + getShippingCode).removeClassName('insuranceForShipping-hidden');
                    }

                    <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice !== lastPrice) {
                        quoteBaseGrandTotal += (newPrice-lastPrice);
                        lastPrice = newPrice;
                    }
                    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
            });
        });
        //]]>
    </script>
<?php endif; ?>
