<?php $_insurance = Mage::getModel('it_insurance/shipping')->getRates(); ?>
<div class="shipping">
    <h2><?php echo $this->__('Estimate Shipping and Tax') ?></h2>
    <div class="shipping-form">
        <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="shipping-zip-form">
            <p class="shipping-desc"><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
            <ul class="form-list">
                <li class="shipping-country">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
                    </div>
                </li>
                <?php // if($this->getStateActive()): ?>
                <li class="shipping-region">
                    <?php /* Removing the conditional check for whether the region is required, because it doesn't work
                    <label for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"' ?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>' ?><?php echo $this->__('State/Province') ?></label>
                    */ ?>
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
                            //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getEstimateRegion()) ?>"  title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text" style="display:none;" />
                    </div>
                </li>
                <?php // endif; ?>
                <?php if($this->getCityActive()): ?>
                    <li class="shipping-region">
                        <label for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->escapeHtml($this->getEstimateCity()) ?>" />
                        </div>
                    </li>
                <?php endif; ?>
                <li class="shipping-postcode">
                    <?php /* Removing the conditional check for whether the postal code is required, because it doesn't work
                    <label for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Zip/Postal Code') ?></label>
                    */ ?>
                    <label for="postcode" class="required"><em>*</em><?php echo $this->__('Zip') ?></label>
                    <div class="input-box">
                        <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->escapeHtml($this->getEstimatePostcode()) ?>" />
                    </div>
                </li>
            </ul>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->quoteEscape($this->__('Estimate')) ?>" onclick="coShippingMethodForm.submit()" class="button2">
                    <span><span><?php echo $this->__('Estimate') ?></span></span>
                </button>
            </div>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
            //]]>
        </script>

        <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
            <form id="co-shipping-method-form" action="<?php echo $this->getUpdateFormActionUrl() ?>">
                <dl class="sp-methods">
                    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                        <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
                        <dd>
                            <ul>
                                <?php foreach ($_rates as $_rate): ?>
                                    <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>>
                                        <?php if ($_rate->getErrorMessage()): ?>
                                            <?php echo $this->escapeHtml($_rate->getErrorMessage()) ?>
                                        <?php else: ?>
                                            <input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                            <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                                -
                                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                                <?php echo $_excl; ?>
                                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                                <?php endif; ?>
                                            </label>
                                        <?php endif ?>
                                        <?php //Insurance ?>
                                        <?php if(isset($_insurance[$_rate->getCode()]) && $_insurance[$_rate->getCode()]['state']):?>
                                            <div id="insuranceForShipping__<?php echo $_rate->getCode() ?>" class="insuranceForShipping <?php echo ($_rate->getCode()===$this->getAddressShippingMethod())?'':'insuranceForShipping-hidden' ?>">
                                                <?php $_insurance_method_price = ($_insurance[$_rate->getCode()]['percent']?($_rate->getPrice()*($_insurance[$_rate->getCode()]['rate']/100)):$_insurance[$_rate->getCode()]['rate']);
                                                $insurance_method_price = $this->getQuote()->getStore()->convertPrice($_insurance_method_price, true)?>
                                                <label><span><?php echo $this->__('Include the insurance?')?>(<span>+<?php echo $insurance_method_price ?></span>)</span>
                                                    <input class="insuranceForShipping__checkbox"
                                                           type="checkbox"
                                                           name="shipping_method_insurance"
                                                           <?php if (($_rate->getCode() === $this->getAddressShippingMethod()) && (float)$this->getQuote()->getShippingAddress()->getInsurance() > 0) echo 'checked' ?>
                                                           value="<?php echo $_insurance_method_price?>">
                                                </label>
                                            </div>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </dd>
                    <?php endforeach; ?>
                </dl>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->quoteEscape($this->__('Update Total')) ?>" class="button" name="do" value="<?php echo $this->__('Update Total') ?>">
                        <span><span><?php echo $this->__('Update Total') ?></span></span>
                    </button>
                </div>
                <?php echo $this->getBlockHtml('formkey') ?>
            </form>
        <?php endif; ?>
        <script type="text/javascript">
            //<![CDATA[
            var coShippingMethodForm = new VarienForm('shipping-zip-form');
            var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

            coShippingMethodForm.submit = function () {
                var country = $F('country');
                var optionalZip = false;

                for (i=0; i < countriesWithOptionalZip.length; i++) {
                    if (countriesWithOptionalZip[i] == country) {
                        optionalZip = true;
                    }
                }
                if (optionalZip) {
                    $('postcode').removeClassName('required-entry');
                }
                else {
                    $('postcode').addClassName('required-entry');
                }
                return VarienForm.prototype.submit.bind(coShippingMethodForm)();
            };

            $$('input[type="radio"][name="estimate_method"]').each(function(el){
                Event.observe(el, 'click', function(){
                    var getShippingCode = el.getValue();
                    $$('input.insuranceForShipping__checkbox').each(function(ell){
                        ell.checked = false;
                    });
                    $$('div.insuranceForShipping').each(function (ell) {
                        ell.addClassName('insuranceForShipping-hidden');
                    });

                    if (el.checked === true) {
                        if($('insuranceForShipping__' + getShippingCode)){
                            $('insuranceForShipping__' + getShippingCode).removeClassName('insuranceForShipping-hidden');
                        }
                    }
                });
            });
            //]]>
        </script>

    </div>
</div>
